name: Claude Issue Assistant

on:
  issues:
    types: [opened, labeled]

jobs:
  ask-claude:
    runs-on: ubuntu-latest
    steps:
      - name: Call Claude API
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_LABEL: ${{ github.event.label.name }}
        run: |
          if [ "$ISSUE_LABEL" != "claude" ] && [ "${{ github.event.action }}" == "labeled" ]; then
            echo "Label is not 'claude', skipping."
            exit 0
          fi

          echo "Sending issue to Claude..."
          RESPONSE=$(curl -s https://api.anthropic.com/v1/messages \
            -H "x-api-key: $ANTHROPIC_API_KEY" \
            -H "content-type: application/json" \
            -d "{
              \"model\": \"claude-3-5-sonnet-20240620\",
              \"max_tokens\": 500,
              \"messages\": [
                {\"role\": \"user\", \"content\": \"GitHub Issue: $ISSUE_TITLE. $ISSUE_BODY. Suggest fixes, next steps, or code.\"}
              ]
            }" | jq -r '.content[0].text')

          echo "Claude response: $RESPONSE"

          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -X POST \
            -d "{\"body\": \"🤖 Claude says:\n\n$RESPONSE\"}" \
            ${{ github.event.issue.comments_url }}