name: Claude Community-Focused Issue Assistant

on:
  issues:
    types: [opened, labeled]
  issue_comment:
    types: [created]

env:
  LUSOTOWN_COMMUNITY: "750+ Portuguese-speaking community members"
  PLATFORM_FOCUS: "Community-first Portuguese cultural platform"

jobs:
  claude-issue-analysis:
    runs-on: ubuntu-latest
    if: >
      (github.event.action == 'opened') ||
      (github.event.action == 'labeled' && github.event.label.name == 'claude') ||
      (github.event.action == 'created' && contains(github.event.comment.body, '@claude'))
    
    permissions:
      issues: write
      contents: read

    steps:
      - name: Checkout for context
        uses: actions/checkout@v4

      - name: Analyze Issue with Claude Community Focus
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Determine trigger context
            let issueTitle = '';
            let issueBody = '';
            let triggerType = '';
            
            if (context.eventName === 'issues') {
              issueTitle = context.payload.issue.title;
              issueBody = context.payload.issue.body || '';
              triggerType = context.payload.action === 'labeled' ? 'labeled with claude' : 'newly opened';
            } else if (context.eventName === 'issue_comment') {
              issueTitle = context.payload.issue.title;
              issueBody = context.payload.issue.body || '';
              triggerType = '@claude mention in comment';
            }
            
            // Skip if labeled but not with 'claude'
            if (context.eventName === 'issues' && context.payload.action === 'labeled' && 
                context.payload.label.name !== 'claude') {
              console.log('Issue labeled but not with "claude" - skipping');
              return;
            }
            
            // Prepare LusoTown context
            const platformContext = `
            LusoTown Portuguese-Speaking Community Platform Context:
            - Serving: ${process.env.LUSOTOWN_COMMUNITY}
            - Mission: ${process.env.PLATFORM_FOCUS}
            - Architecture: Next.js 14, Supabase+PostGIS, streamlined components
            - Key Principles: Zero hardcoding, bilingual EN/PT, mobile-first, Portuguese cultural authenticity
            - University Partnerships: 8 institutions across UK
            - Community Focus: Events, business directory, cultural connections, transport coordination
            
            Development Standards:
            - All data from config files (zero hardcoding policy)
            - "Portuguese-speaking community" terminology (not "Portuguese community")
            - UK-wide scope (not London-only)
            - Mobile-first design for community members
            - Cultural authenticity across all 8 PALOP nations
            `;
            
            const prompt = `${platformContext}
            
            GitHub Issue Analysis Request:
            **Title**: ${issueTitle}
            **Body**: ${issueBody}
            **Trigger**: ${triggerType}
            
            Please analyze this issue for the LusoTown Portuguese-speaking community platform:
            
            1. **Community Impact**: How does this issue affect our 750+ Portuguese-speaking community members?
            2. **Priority Assessment**: Is this critical for community platform operations?
            3. **Cultural Considerations**: Are there Portuguese cultural authenticity implications?
            4. **Technical Solution**: Specific actionable steps following our zero-hardcoding and community-first principles
            5. **Mobile Impact**: Does this affect mobile experience for community members?
            
            Provide practical recommendations that prioritize community value and Portuguese cultural authenticity.
            Be developer-friendly but focus on how solutions benefit the Portuguese-speaking community.
            
            If this is a bug report, suggest debugging steps.
            If this is a feature request, evaluate community benefit.
            If this is a question, provide helpful guidance within our platform context.
            `;
            
            try {
              const response = await fetch('https://api.anthropic.com/v1/messages', {
                method: 'POST',
                headers: {
                  'x-api-key': '${{ secrets.ANTHROPIC_API_KEY }}',
                  'content-type': 'application/json',
                  'anthropic-version': '2023-06-01'
                },
                body: JSON.stringify({
                  model: 'claude-3-5-sonnet-20241022',
                  max_tokens: 2000,
                  messages: [{
                    role: 'user',
                    content: prompt
                  }]
                })
              });
              
              if (!response.ok) {
                throw new Error(`Claude API error: ${response.status} ${response.statusText}`);
              }
              
              const data = await response.json();
              const analysis = data.content[0].text;
              
              // Post Claude's analysis
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: `## 🤖🇵🇹 Claude Community Platform Analysis

${analysis}

---
*This analysis considers LusoTown's community-first architecture and Portuguese cultural authenticity standards. Triggered by: ${triggerType}*`
              });
              
            } catch (error) {
              console.error('Claude analysis failed:', error);
              
              // Provide fallback response with community context
              const fallbackResponse = `## 🤖🇵🇹 Claude Analysis (Fallback Mode)

I'm currently unable to provide detailed analysis, but here are some general guidelines for LusoTown development:

### 🎯 Community-First Principles
- **Priority**: How does this benefit our 750+ Portuguese-speaking community members?
- **Cultural Authenticity**: Use "Portuguese-speaking community" terminology and UK-wide scope
- **Mobile-First**: Ensure mobile accessibility for community members

### 🔧 Technical Standards  
- **Zero Hardcoding**: Import all data from \`/web-app/src/config/\` files
- **Bilingual Support**: Implement EN/PT translations
- **Quality Gates**: Must pass hardcoding audit, lint, and TypeScript checks

### 📱 Development Process
1. Check if change serves Portuguese community needs
2. Validate cultural authenticity and inclusion  
3. Test mobile experience at 375px, 768px, 1024px
4. Run quality checks: \`npm run audit:hardcoding && npm run lint\`

For detailed guidance, please refer to our [Community Guidelines](.github/claude-config/community-guidelines.md) and development documentation.

*Claude analysis temporarily unavailable - please follow community-first development principles.*`;
              
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: fallbackResponse
              });
            }