import { buildUnsplashUrl } from '@/config'
// Beginner-Friendly Business Events for Portuguese Community in London

export const businessEventsLondon = [
  // STARTING YOUR FIRST BUSINESS
  {
    id: 'london-basic-business-workshop-1',
    title: 'Starting Your First Business: Complete Beginner\'s Guide',
    description: 'Learn the basics of starting a business in the UK. Perfect for complete beginners with no business experience. Simple, practical steps to get started.',
    longDescription: 'Comece o seu primeiro negócio! A friendly, beginner-focused workshop for Portuguese speakers who want to start their first business in the UK.\n\nLed by Maria Santos, a Portuguese business mentor who helps beginners start their first companies with simple, practical advice.\n\nWhat you\'ll learn:\n\n• How to find your first business idea (no experience needed)\n• Basic business registration in the UK (step-by-step guide)\n• Understanding taxes and paperwork (simplified)\n• Creating a simple business plan (template provided)\n• Finding your first customers\n• Basic marketing on social media\n• Managing money and simple bookkeeping\n• Legal requirements for UK businesses\n\nReal examples:\n• Portuguese cafe owner who started with £500\n• Cleaning service that grew to 5 employees\n• Online tutoring business started from home\n• Handmade crafts business on Etsy\n\nPerfect for:\n• Complete beginners with no business experience\n• People wanting to start small, simple businesses\n• Those looking for extra income\n• Anyone scared of starting but wanting to try\n\nIncludes:\n• Simple business plan template\n• Checklist of steps to start\n• Directory of helpful UK business resources\n• Group support chat for questions\n• 30 days of email tips\n\nNo laptop needed - just bring a notebook and enthusiasm!',
    date: '2025-09-15',
    time: '10:00',
    endTime: '15:00',
    location: 'Portuguese Community Centre',
    address: '12 Little Portugal, London SW8 1XE',
    coordinates: { lat: 51.4851, lng: -0.1294 },
    category: 'Business Basics',
    subcategory: 'Getting Started',
    tags: ['beginner business', 'first business', 'UK business', 'simple', 'practical', 'portuguese'],
    hostId: 'host-maria-santos',
    hostName: 'Maria Santos',
    hostBio: 'Portuguese business mentor specializing in helping complete beginners start their first small businesses',
    membershipRequired: 'free',
    price: 25,
    currency: 'GBP',
    maxAttendees: 20,
    minAttendees: 6,
    currentAttendees: 14,
    waitlistCount: 3,
    status: 'published',
    featured: true,
    images: [
      buildUnsplashUrl('photo-1556740738-b6a63e27c4df?w=600&h=400&fit=crop&auto=format'),
      buildUnsplashUrl('photo-1559136555-9303baea8ebd?w=600&h=400&fit=crop&auto=format')
    ],
    whatToBring: ['Notebook', 'Pen', 'Business ideas (even just rough thoughts)'],
    dresscode: 'Casual and comfortable',
    ageRestriction: '18+ (all backgrounds welcome - no business experience required)',
    skillLevel: 'complete beginner',
    accessibility: ['Wheelchair accessible venue', 'All materials provided', 'Portuguese/English support'],
    allowWaitlist: true,
    requiresApproval: false,
    refundPolicy: 'Full refund 3 days in advance',
    lastBookingTime: '24'
  },

  // SIMPLE SOCIAL MEDIA
  {
    id: 'london-basic-social-media-workshop-1',
    title: 'Social Media for Small Business: Instagram & Facebook Basics',
    description: 'Learn simple social media marketing for your business. Perfect for beginners who want to use Instagram and Facebook to find customers.',
    longDescription: 'Aprenda redes sociais para o seu negócio! A simple, beginner-friendly workshop for Portuguese speakers who want to use social media to promote their small business.\n\nLed by Ana Silva, a Portuguese marketing teacher who helps small business owners get started with social media.\n\nWhat you\'ll learn:\n\n• Setting up business accounts on Instagram and Facebook\n• Taking good photos with your phone\n• Writing simple posts that get attention\n• Finding local customers online\n• Basic advertising (£5-10 per day budgets)\n• Responding to messages and comments\n• Planning your posts ahead of time\n• Simple analytics to see what works\n\nReal examples:\n• Portuguese bakery that doubled customers using Instagram\n• Cleaning service that gets bookings from Facebook\n• Handmade jewelry business on Instagram\n• Personal trainer who finds clients on social media\n\nPerfect for:\n• Small business owners who are new to social media\n• People who have accounts but don\'t know how to use them for business\n• Anyone wanting to learn simple marketing\n• Those on a tight marketing budget\n\nIncludes:\n• Simple social media plan template\n• Photo tips checklist\n• List of hashtags for different businesses\n• Content planning calendar\n• Step-by-step guides you can keep\n\nBring your phone - we\'ll practice during the workshop!',
    date: '2025-09-22',
    time: '14:00',
    endTime: '17:00',
    location: 'Portuguese Community Centre',
    address: '12 Little Portugal, London SW8 1XE',
    coordinates: { lat: 51.4851, lng: -0.1294 },
    category: 'Digital Marketing',
    subcategory: 'Social Media Basics',
    tags: ['social media', 'instagram', 'facebook', 'marketing', 'beginner', 'small business'],
    hostId: 'host-ana-silva',
    hostName: 'Ana Silva',
    hostBio: 'Portuguese marketing teacher specializing in simple social media strategies for small businesses',
    membershipRequired: 'free',
    price: 15,
    currency: 'GBP',
    maxAttendees: 15,
    minAttendees: 5,
    currentAttendees: 9,
    waitlistCount: 2,
    status: 'published',
    featured: false,
    images: [
      buildUnsplashUrl('photo-1611262588024-d12430b98920?w=600&h=400&fit=crop&auto=format'),
      buildUnsplashUrl('photo-1493612276216-ee3925520721?w=600&h=400&fit=crop&auto=format')
    ],
    whatToBring: ['Smartphone', 'Notebook', 'Any business photos you have'],
    dresscode: 'Casual and comfortable',
    ageRestriction: '18+ (all backgrounds welcome)',
    skillLevel: 'complete beginner',
    accessibility: ['Wheelchair accessible venue', 'All materials provided', 'Portuguese/English support'],
    allowWaitlist: true,
    requiresApproval: false,
    refundPolicy: 'Full refund 2 days in advance',
    lastBookingTime: '24'
  },

  // BASIC MONEY MANAGEMENT
  {
    id: 'london-basic-money-workshop-1',
    title: 'Managing Money in the UK: Banking and Saving Basics',
    description: 'Learn the basics of managing money in the UK. Perfect for anyone who wants to understand UK banking, saving, and simple budgeting.',
    longDescription: 'Gerencie o seu dinheiro no Reino Unido! A practical workshop for Portuguese speakers who want to understand basic money management in the UK.\n\nLed by João Costa, a Portuguese financial adviser who helps people with simple money management and UK banking.\n\nWhat you\'ll learn:\n\n• Opening bank accounts in the UK (which banks are best)\n• Understanding UK credit scores and how to improve them\n• Simple budgeting (track your money easily)\n• Different types of savings accounts\n• Basic insurance you might need (home, car, health)\n• Simple ways to save money on bills\n• Understanding loans and mortgages (the basics)\n• Building an emergency fund (even with small amounts)\n\nReal examples:\n• Portuguese family who saved £5,000 in their first year\n• Simple budgeting system that works with any income\n• How to improve your credit score in 6 months\n• Best UK bank accounts for Portuguese speakers\n\nPerfect for:\n• Anyone new to UK banking\n• People who want to save money but don\'t know how\n• Those confused by UK financial system\n• Anyone wanting to improve their money management\n\nIncludes:\n• Simple budget planning worksheet\n• UK banking comparison guide\n• Money-saving tips checklist\n• Emergency fund calculator\n• List of helpful financial apps\n\nNo financial experience needed - just bring questions about money!',
    date: '2025-10-06',
    time: '11:00',
    endTime: '14:00',
    location: 'Portuguese Community Centre',
    address: '12 Little Portugal, London SW8 1XE',
    coordinates: { lat: 51.4851, lng: -0.1294 },
    category: 'Personal Finance',
    subcategory: 'Banking & Saving',
    tags: ['money management', 'UK banking', 'saving', 'budgeting', 'credit score', 'beginner'],
    hostId: 'host-joao-costa',
    hostName: 'João Costa',
    hostBio: 'Portuguese financial adviser specializing in basic money management for Portuguese community',
    membershipRequired: 'free',
    price: 20,
    currency: 'GBP',
    maxAttendees: 18,
    minAttendees: 6,
    currentAttendees: 12,
    waitlistCount: 4,
    status: 'published',
    featured: false,
    images: [
      buildUnsplashUrl('photo-1579621970563-ebec7560ff3e?w=600&h=400&fit=crop&auto=format'),
      buildUnsplashUrl('photo-1633158829585-23ba8f7c8caf?w=600&h=400&fit=crop&auto=format')
    ],
    whatToBring: ['Notebook', 'Calculator (or phone)', 'Any bank letters or bills you have questions about'],
    dresscode: 'Casual and comfortable',
    ageRestriction: '18+ (all backgrounds welcome)',
    skillLevel: 'complete beginner',
    accessibility: ['Wheelchair accessible venue', 'All materials provided', 'Portuguese/English support'],
    allowWaitlist: true,
    requiresApproval: false,
    refundPolicy: 'Full refund 2 days in advance',
    lastBookingTime: '24'
  },

  // BASIC COMPUTER SKILLS
  {
    id: 'london-basic-computer-workshop-1',
    title: 'Computer Skills for Small Business: Email, Documents & Online Banking',
    description: 'Learn basic computer skills for business. Perfect for beginners who want to feel confident using computers, email, and the internet for business.',
    longDescription: 'Aprenda informática básica para negócios! A gentle introduction to computers for Portuguese speakers who want to use technology confidently in their business.\n\nLed by Carlos Mendes, a Portuguese IT teacher who specializes in helping beginners with computers.\n\nWhat you\'ll learn:\n\n• Basic computer skills (if you\'re nervous about computers)\n• Setting up professional email addresses\n• Writing business emails that look professional\n• Creating simple documents (letters, invoices, flyers)\n• Using the internet safely for business\n• Online banking basics\n• Simple online marketing (creating basic websites)\n• Backing up important business information\n\nReal examples:\n• Portuguese restaurant owner who now takes online orders\n• Cleaning business that sends professional invoices\n• Handyman who created his own simple website\n• Shop owner who learned online banking\n\nPerfect for:\n• Anyone nervous about using computers for business\n• People who want to learn at their own pace\n• Small business owners who need basic computer skills\n• Those wanting to feel more confident with technology\n\nIncludes:\n• Step-by-step guides you can take home\n• Practice on real computers during workshop\n• Email setup help\n• Simple website templates\n• List of free tools you can use\n\nWe provide computers for practice - or bring your laptop if you have one!',
    date: '2025-10-13',
    time: '10:00',
    endTime: '16:00',
    location: 'Local Library Computer Room',
    address: '25 Stockwell Road, London SW9 9AU',
    coordinates: { lat: 51.4720, lng: -0.1127 },
    category: 'Digital Skills',
    subcategory: 'Basic Computer Skills',
    tags: ['computer skills', 'email', 'documents', 'internet', 'beginner', 'technology'],
    hostId: 'host-carlos-mendes',
    hostName: 'Carlos Mendes',
    hostBio: 'Portuguese IT teacher specializing in gentle computer training for beginners and small business owners',
    membershipRequired: 'free',
    price: 30,
    currency: 'GBP',
    maxAttendees: 12,
    minAttendees: 4,
    currentAttendees: 8,
    waitlistCount: 2,
    status: 'published',
    featured: false,
    images: [
      buildUnsplashUrl('photo-1516321318423-f06f85e504b3?w=600&h=400&fit=crop&auto=format'),
      buildUnsplashUrl('photo-1551288049-bebda4e38f71?w=600&h=400&fit=crop&auto=format')
    ],
    whatToBring: ['Notebook for taking notes', 'Any business documents you want to practice with', 'Reading glasses if you need them'],
    dresscode: 'Comfortable and casual',
    ageRestriction: '18+ (all skill levels welcome)',
    skillLevel: 'complete beginner',
    accessibility: ['Wheelchair accessible venue', 'Computers provided', 'Large screen displays', 'Portuguese/English support'],
    allowWaitlist: true,
    requiresApproval: false,
    refundPolicy: 'Full refund 3 days in advance',
    lastBookingTime: '48'
  },

  // SIMPLE NETWORKING
  {
    id: 'london-basic-networking-workshop-1',
    title: 'Business Networking for Beginners: Making Connections in London',
    description: 'Learn how to network and make business connections. Perfect for shy people or anyone new to business networking in London.',
    longDescription: 'Faça conexões de negócio em Londres! A friendly workshop for Portuguese speakers who want to learn networking but feel nervous or don\'t know where to start.\n\nLed by Sofia Pereira, a Portuguese business coach who helps shy people become confident networkers.\n\nWhat you\'ll learn:\n\n• How to introduce yourself confidently\n• What to say at networking events (simple conversation starters)\n• Finding the right networking events in London\n• Following up with new contacts (without being pushy)\n• Building long-term business relationships\n• Networking online (LinkedIn basics)\n• Overcoming shyness and nerves\n• Portuguese business etiquette vs UK business culture\n\nReal examples:\n• Portuguese graphic designer who found clients through networking\n• Shy accountant who built a successful practice\n• Restaurant owner who partnered with other Portuguese businesses\n• Cleaner who got referrals from networking\n\nPerfect for:\n• People who are shy or nervous about networking\n• Anyone new to business networking\n• Those wanting to grow their business through connections\n• Portuguese speakers wanting to understand UK business culture\n\nIncludes:\n• Practice networking during the workshop\n• Simple conversation starter cards\n• List of Portuguese-friendly networking events in London\n• Follow-up email templates\n• LinkedIn profile tips\n\nWe\'ll practice networking in a safe, friendly environment!',
    date: '2025-10-20',
    time: '13:00',
    endTime: '16:00',
    location: 'Portuguese Community Centre',
    address: '12 Little Portugal, London SW8 1XE',
    coordinates: { lat: 51.4851, lng: -0.1294 },
    category: 'Business Networking',
    subcategory: 'Communication Skills',
    tags: ['networking', 'communication', 'business connections', 'confidence', 'beginner'],
    hostId: 'host-sofia-pereira',
    hostName: 'Sofia Pereira',
    hostBio: 'Portuguese business coach specializing in helping introverts and beginners with business networking',
    membershipRequired: 'free',
    price: 18,
    currency: 'GBP',
    maxAttendees: 16,
    minAttendees: 6,
    currentAttendees: 11,
    waitlistCount: 3,
    status: 'published',
    featured: false,
    images: [
      buildUnsplashUrl('photo-1515187029135-18ee286d815b?w=600&h=400&fit=crop&auto=format'),
      buildUnsplashUrl('photo-1552664730-d307ca884978?w=600&h=400&fit=crop&auto=format')
    ],
    whatToBring: ['Business cards if you have them (we can help make simple ones)', 'Notebook', 'Comfortable shoes for mingling'],
    dresscode: 'Smart casual (practice for real networking events)',
    ageRestriction: '18+ (all confidence levels welcome)',
    skillLevel: 'complete beginner',
    accessibility: ['Wheelchair accessible venue', 'All materials provided', 'Portuguese/English support'],
    allowWaitlist: true,
    requiresApproval: false,
    refundPolicy: 'Full refund 2 days in advance',
    lastBookingTime: '24'
  }
]