// Professional Business & Educational Events for Portuguese Community in London

export const businessEventsLondon = [
  // AI & TECHNOLOGY WORKSHOPS
  {
    id: 'london-ai-coding-workshop-1',
    title: 'AI-Powered Website Building Workshop: Code with ChatGPT & Claude',
    description: 'Learn to build professional websites using AI tools like ChatGPT and Claude. Master modern web development with Portuguese-speaking tech professionals in London\'s financial district.',
    longDescription: 'Revolucione sua carreira tech! Join Portuguese-speaking professionals for an intensive 6-hour workshop where you\'ll learn to build complete websites using cutting-edge AI coding assistants like ChatGPT, Claude, and GitHub Copilot.\n\nLed by Pedro Almeida, a Portuguese senior software engineer at Revolut, this hands-on workshop covers:\n\n• AI-assisted coding fundamentals and prompt engineering for developers\n• Building responsive websites with HTML, CSS, JavaScript using AI guidance\n• Integrating modern frameworks (React, Next.js) with AI code generation\n• Database design and API creation with AI assistance\n• Deployment strategies for business websites using Vercel and Netlify\n• Business applications: creating client websites, e-commerce platforms, SaaS products\n\nReal Portuguese business case studies including how Farfetch, OutSystems, and other Portuguese unicorns leverage AI in development. Perfect for entrepreneurs, career changers, and professionals wanting to add tech skills.\n\nWorkshop includes:\n• Laptop setup and development environment configuration\n• Access to premium AI coding tools (£150 value)\n• Complete source code and templates\n• Portuguese tech community networking lunch\n• 30-day follow-up support group\n• Certificate of completion\n\nLeave with a fully functional website and the skills to build more. No prior coding experience required - just enthusiasm for learning!',
    date: '2025-09-15',
    time: '09:00',
    endTime: '17:00',
    location: 'WeWork Moorgate',
    address: '2 Finsbury Ave, London EC2M 2PP',
    coordinates: { lat: 51.5207, lng: -0.0869 },
    category: 'Technology & AI',
    subcategory: 'Coding Workshops',
    tags: ['AI coding', 'website development', 'ChatGPT', 'Claude', 'entrepreneurship', 'professional development'],
    hostId: 'host-pedro-almeida',
    hostName: 'Pedro Almeida',
    hostBio: 'Senior Software Engineer at Revolut, Portuguese tech mentor specializing in AI-assisted development',
    membershipRequired: 'standard',
    price: 295,
    currency: 'GBP',
    maxAttendees: 16,
    minAttendees: 8,
    currentAttendees: 12,
    waitlistCount: 6,
    status: 'published',
    featured: true,
    images: [
      'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600&h=400&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=600&h=400&fit=crop&auto=format'
    ],
    whatToBring: ['Laptop (Windows/Mac)', 'Notebook for ideas', 'Business cards for networking'],
    dresscode: 'Smart casual',
    ageRestriction: '18+ (adult professional development)',
    skillLevel: 'beginner to intermediate',
    accessibility: ['Wheelchair accessible venue', 'All materials provided'],
    allowWaitlist: true,
    requiresApproval: false,
    refundPolicy: 'Full refund 7 days in advance, 50% refund 48h in advance',
    lastBookingTime: '24'
  },
  
  // BUSINESS STRATEGY WORKSHOPS
  {
    id: 'london-business-strategy-workshop-1',
    title: 'Portuguese Entrepreneurs Scaling Workshop: From UK to Global Markets',
    description: 'Strategic business scaling workshop for Portuguese entrepreneurs. Learn market expansion, funding strategies, and legal frameworks for growing your business from London to international markets.',
    longDescription: 'Expanda seu negócio além fronteiras! Join successful Portuguese entrepreneurs and business advisors for an intensive strategy workshop focused on scaling your business from the UK to global markets.\n\nLed by Maria Santos, Portuguese founder of three successful London startups (two exits), and João Reis, business advisor who helped 50+ Portuguese companies expand internationally.\n\nWorkshop modules:\n\n• Market research and validation for international expansion\n• UK business structures and tax optimization strategies\n• Funding landscape: from angel investment to Series A\n• Legal frameworks for operating across Portugal, UK, and EU\n• Building remote teams across cultures and time zones\n• Digital marketing strategies for Portuguese businesses\n• Case studies: Portuguese companies that scaled globally\n\nFeatures real success stories from Portuguese entrepreneurs:\n• How Talkdesk scaled from Lisbon to $10B valuation\n• OutSystems\' journey from Porto to NASDAQ\n• Smaller success stories from London\'s Portuguese business community\n\nIncludes:\n• Business assessment toolkit\n• Legal document templates\n• Investor pitch deck framework\n• Direct access to Portuguese investor network\n• 6-month mentorship program enrollment option\n• Luxury networking lunch at Private Members Club\n\nPerfect for business owners with £100K+ annual revenue looking to scale, professionals considering entrepreneurship, or investors wanting to understand Portuguese business culture.',
    date: '2025-09-22',
    time: '09:30',
    endTime: '16:30',
    location: 'The Shard - Level 17',
    address: '32 London Bridge St, London SE1 9SG',
    coordinates: { lat: 51.5045, lng: -0.0865 },
    category: 'Business & Entrepreneurship',
    subcategory: 'Strategy & Scaling',
    tags: ['entrepreneurship', 'business scaling', 'international expansion', 'investment', 'Portuguese business'],
    hostId: 'host-maria-santos',
    hostName: 'Maria Santos & João Reis',
    hostBio: 'Successful Portuguese entrepreneurs and business advisors with 20+ years London business experience',
    membershipRequired: 'premium',
    price: 485,
    currency: 'GBP',
    maxAttendees: 20,
    minAttendees: 10,
    currentAttendees: 15,
    waitlistCount: 8,
    status: 'published',
    featured: true,
    images: [
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&h=400&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1521791136064-7986c2920216?w=600&h=400&fit=crop&auto=format'
    ],
    whatToBring: ['Business cards', 'Current business financial summary', 'Expansion goals and questions'],
    dresscode: 'Business formal',
    ageRestriction: '21+ (established business professionals)',
    skillLevel: 'intermediate to advanced',
    accessibility: ['Premium venue with full accessibility', 'Dietary requirements accommodated'],
    allowWaitlist: true,
    requiresApproval: true,
    refundPolicy: 'Full refund 14 days in advance due to premium venue and materials',
    lastBookingTime: '72'
  },

  // FINANCIAL LITERACY & INVESTMENT
  {
    id: 'london-investment-masterclass-1',
    title: 'UK Property Investment Masterclass: Portuguese Investors Guide',
    description: 'Comprehensive property investment education for Portuguese professionals. Learn UK market dynamics, tax strategies, and legal frameworks for building wealth through London real estate.',
    longDescription: 'Construa riqueza no mercado imobiliário britânico! Join experienced Portuguese property investors and UK legal experts for a comprehensive masterclass on building wealth through London real estate.\n\nLed by Carlos Ferreira (Portuguese property investor with £5M+ portfolio) and Sarah Mitchell (UK property solicitor specializing in international clients).\n\nMasterclass covers:\n\n• UK property market analysis and cycle understanding\n• Best areas for Portuguese investors: cash flow vs appreciation\n• Buy-to-let strategies and rental yield optimization\n• Commercial property investment fundamentals\n• Tax strategies: capital gains, stamp duty, and offshore structures\n• Legal frameworks and due diligence processes\n• Financing options for foreign nationals and Portuguese residents\n• Property management and scaling your portfolio\n\nReal case studies:\n• How Portuguese investors built £1M+ portfolios in 5 years\n• Successful commercial property investments in London\n• Common mistakes and how to avoid them\n• Brexit impact analysis and opportunities\n\nIncludes:\n• Property investment calculator and analysis tools\n• Legal document templates and checklists\n• Preferred supplier network (solicitors, accountants, agents)\n• Market research reports (£500 value)\n• 3-month email support for questions\n• Investment opportunity deal flow access\n\nPerfect for high-earning professionals, business owners with £50K+ investment capital, or anyone serious about building wealth through UK property.',
    date: '2025-10-06',
    time: '10:00',
    endTime: '16:00',
    location: 'Canary Wharf Conference Centre',
    address: '22-25 Canada Square, London E14 5LQ',
    coordinates: { lat: 51.5054, lng: -0.0235 },
    category: 'Finance & Investment',
    subcategory: 'Property Investment',
    tags: ['property investment', 'UK real estate', 'wealth building', 'tax strategies', 'Portuguese investors'],
    hostId: 'host-carlos-ferreira',
    hostName: 'Carlos Ferreira & Sarah Mitchell',
    hostBio: 'Experienced property investor and UK solicitor team specializing in Portuguese investor success',
    membershipRequired: 'premium',
    price: 395,
    currency: 'GBP',
    maxAttendees: 25,
    minAttendees: 12,
    currentAttendees: 18,
    waitlistCount: 7,
    status: 'published',
    featured: true,
    images: [
      'https://images.unsplash.com/photo-1560520653-9e0e4c89eb11?w=600&h=400&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=600&h=400&fit=crop&auto=format'
    ],
    whatToBring: ['Financial documents for portfolio review', 'Investment goals and budget', 'Notebook for detailed notes'],
    dresscode: 'Business casual',
    ageRestriction: '25+ (investment-focused professionals)',
    skillLevel: 'beginner to intermediate',
    accessibility: ['Modern accessible venue', 'Materials available in Portuguese'],
    allowWaitlist: true,
    requiresApproval: true,
    refundPolicy: 'Full refund 10 days in advance, no refund 48h before due to material preparation',
    lastBookingTime: '72'
  },

  // DIGITAL MARKETING & E-COMMERCE
  {
    id: 'london-digital-marketing-workshop-1',
    title: 'E-commerce Mastery: Build Your Online Business with AI Marketing',
    description: 'Complete e-commerce and digital marketing workshop for Portuguese entrepreneurs. Learn to build, market, and scale online businesses using modern AI tools and strategies.',
    longDescription: 'Domine o comércio digital! Join Portuguese digital marketing experts for an intensive workshop on building and scaling e-commerce businesses using cutting-edge AI marketing tools.\n\nLed by Ana Rodrigues (Portuguese founder of 3 successful e-commerce brands) and tech team from Portuguese digital agency that manages £2M+ in ad spend.\n\nWorkshop modules:\n\n• E-commerce platform selection and setup (Shopify, WooCommerce, custom)\n• Product research and validation using AI tools\n• AI-powered content creation: product descriptions, ads, social media\n• Advanced Facebook and Google Ads strategies\n• Email marketing automation and customer retention\n• Influencer marketing and partnership strategies\n• Conversion rate optimization using data and AI\n• International shipping and payment processing\n• Brand building and customer acquisition\n\nReal business case studies:\n• How Portuguese brands successfully entered UK markets\n• E-commerce success stories: from £0 to £500K+ annual revenue\n• AI tools that reduced marketing costs by 60%\n• Cross-border e-commerce between Portugal and UK\n\nPractical outcomes:\n• Set up complete e-commerce store during workshop\n• Launch first AI-generated marketing campaign\n• Create automated email marketing funnel\n• Develop 90-day business growth plan\n\nIncludes:\n• Premium tool access (worth £300)\n• Marketing templates and automation setups\n• Product sourcing contacts and supplier network\n• 60-day implementation support group\n• Advanced training video library\n\nPerfect for aspiring entrepreneurs, existing business owners wanting online presence, or marketing professionals upgrading skills.',
    date: '2025-10-13',
    time: '09:00',
    endTime: '17:30',
    location: 'Google Campus London',
    address: '4-5 Bonhill St, London EC2A 4BX',
    coordinates: { lat: 51.5248, lng: -0.0854 },
    category: 'Digital Marketing',
    subcategory: 'E-commerce & AI',
    tags: ['e-commerce', 'digital marketing', 'AI marketing', 'online business', 'entrepreneurship'],
    hostId: 'host-ana-rodrigues',
    hostName: 'Ana Rodrigues',
    hostBio: 'Portuguese e-commerce entrepreneur and digital marketing expert with 3 successful online businesses',
    membershipRequired: 'standard',
    price: 345,
    currency: 'GBP',
    maxAttendees: 18,
    minAttendees: 10,
    currentAttendees: 14,
    waitlistCount: 5,
    status: 'published',
    featured: true,
    images: [
      'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=600&h=400&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=600&h=400&fit=crop&auto=format'
    ],
    whatToBring: ['Laptop with good internet', 'Business ideas or existing products', 'Payment method for tool subscriptions'],
    dresscode: 'Smart casual',
    ageRestriction: '18+ (professional business focus)',
    skillLevel: 'beginner to intermediate',
    accessibility: ['Tech-friendly venue', 'All software provided'],
    allowWaitlist: true,
    requiresApproval: false,
    refundPolicy: 'Full refund 5 days in advance, 50% refund 24h before',
    lastBookingTime: '24'
  },

  // PROFESSIONAL NETWORKING
  {
    id: 'london-executive-networking-1',
    title: 'Portuguese Executives Network: C-Suite & Senior Leadership Gathering',
    description: 'Exclusive networking event for Portuguese C-suite executives, senior managers, and business leaders in London. Strategic discussions, partnership opportunities, and high-level connections.',
    longDescription: 'Rede exclusiva de liderança portuguesa! Join London\'s most accomplished Portuguese executives and business leaders for an exclusive evening of strategic networking, insights sharing, and partnership development.\n\nThis invitation-only event brings together CEOs, CTOs, Managing Directors, Senior Partners, and C-suite executives from the Portuguese business community across London\'s major industries.\n\nEvening format:\n\n• Welcome reception with premium Portuguese wines\n• Keynote: "Portuguese Leadership in Global Markets" by Paulo Silva (Portuguese CEO of major UK fintech)\n• Strategic roundtables by industry: Finance, Tech, Real Estate, Consulting, Healthcare\n• Partnership and collaboration speed networking\n• Investment opportunities showcase\n• Closing dinner with guest speaker from Portuguese Embassy\n\nAttendee profile (verified):\n• C-suite executives and senior leadership roles\n• Business owners with £1M+ annual revenue\n• Investment professionals and fund managers\n• Senior partners in professional services\n• Scale-up founders with significant funding\n\nBenefits:\n• Access to exclusive Portuguese executive network\n• Partnership and investment opportunity pipeline\n• Strategic business advice from peers\n• Cultural bridge-building for international expansion\n• Quarterly follow-up events and private dinners\n\nVenue: Private dining room at prestigious London members\' club with Portuguese wine selection curated by sommelier João Ramos.\n\nStrictly limited to 30 executives to ensure meaningful connections and strategic conversations.',
    date: '2025-10-28',
    time: '18:30',
    endTime: '22:30',
    location: 'The Cavalry & Guards Club',
    address: '127 Piccadilly, London W1J 7PX',
    coordinates: { lat: 51.5074, lng: -0.1431 },
    category: 'Executive Networking',
    subcategory: 'C-Suite & Leadership',
    tags: ['executive networking', 'C-suite', 'business leadership', 'partnerships', 'investment'],
    hostId: 'host-executive-network',
    hostName: 'Portuguese Executive Network London',
    hostBio: 'Exclusive network of Portuguese C-suite executives and business leaders in London',
    membershipRequired: 'executive',
    price: 195,
    currency: 'GBP',
    maxAttendees: 30,
    minAttendees: 20,
    currentAttendees: 25,
    waitlistCount: 12,
    status: 'published',
    featured: true,
    images: [
      'https://images.unsplash.com/photo-1511578314322-379afb476865?w=600&h=400&fit=crop&auto=format',
      'https://images.unsplash.com/photo-1515187029135-18ee286d815b?w=600&h=400&fit=crop&auto=format'
    ],
    whatToBring: ['Business cards', 'Company profile or pitch deck', 'Formal attire'],
    dresscode: 'Black tie / Formal business',
    ageRestriction: '30+ (C-suite and senior leadership only)',
    skillLevel: 'executive level',
    accessibility: ['Historic venue with limited accessibility', 'Concierge assistance available'],
    allowWaitlist: true,
    requiresApproval: true,
    refundPolicy: 'No refunds due to exclusive venue and catering requirements',
    lastBookingTime: '168'
  }
]

export default businessEventsLondon